### ISSUE TITLE
rendering a custom row even if there are zero items to show

### ISSUE THREAD

**Issue by thujone** [avin/react-vt-table#3]
HI, I have a row of filters that I'm rendering immediately underneath the header row. It looks like this:

```
    if (index === 0) {
        return (
            <div
                {...{ style: { ...style, width: getRowWidth(), lineHeight: style.height + 'px' } }}
                className="CustomRow"
            >
              {filters.map( (filter, i) => {
                const filterProps = filter.props;
                const FilterComponent = filter.component;
                
                return (
                  <span {...{ style: { ...style, width: '100px', left: 100 * i + 'px', lineHeight: style.height + 'px' } }}>
                    <FilterComponent key={i} {...filter.props}>
                      {filter.props.children && filter.props.children}
                    </FilterComponent>
                  </span>
                )
                              
              })}
            </div>
        );
    }
```

The issue I have is that if I enter text into the filter that changes the number of items to render to 0, then the CustomRow I'm rendering also disappears. I'd like for that CustomRow to always stay put, even when there are no results to render. Is this possible?

**Comment by thujone** [comment]
If there's a way to render a custom row as a header row instead of as part of the VTList, I guess that would be ideal.

**Comment by avin** [comment]
Hey man! 

* You can append your filter components to columns headers using `sortIndicatorRenderer`
Check this code https://github.com/avin/react-vt-table/blob/master/src/lib/Header/Header.js#L79
You can add anything you want to header's column row with this function - it doesn't have to be sorting.

* Another way - use `columnHeaderCellRenderer` of `Column` - you can add your custom elements there

* BUT if your filter row does not fit columns headers - you can just add fake-row at tabel content - it's also OK.

**Comment by thujone** [comment]
Awesome, thanks for the info. I'll try the sortIndicatorRenderer today and let you know how it goes. Great library!
